baseURL: https://manoj.ink/
languageCode: en-us
title: Manoj Nayak
theme: "PaperMod"

params:
    homeInfoParams:
        Title: Manoj Nayak's Desk 🖥️ 
        Content: Always work on an empty stomach.

    socialIcons: # optional
        - name: "github"
          url: "https://github.com/exist2021"
        - name: "linkedin"
          url: "www.linkedin.com/comm/mynetwork/discovery-see-all?usecase=PEOPLE_FOLLOWS&followMember=manojrnayak"
        - name: "twitter"
          url: "https://twitter.com/manojnayak"
        - name: "kofi" 
          url: "https://www.buymeacoffee.com/Manoj"
        - name: "rss"
          url: "https://manoj.work/index.xml"
    ShowReadingTime: true
    author: "Manoj Nayak"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 20
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 20
